# Generated by Django 4.2.7 on 2025-10-20 02:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Comedor')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('direccion', models.CharField(max_length=300, verbose_name='Dirección')),
                ('barrio', models.CharField(blank=True, max_length=100, verbose_name='Barrio')),
                ('latitud', models.FloatField(help_text='Ej: 3.4516', verbose_name='Latitud')),
                ('longitud', models.FloatField(help_text='Ej: -76.5320', verbose_name='Longitud')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('celular', models.CharField(blank=True, max_length=50, verbose_name='Celular')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('capacidad_personas', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacidad de Personas')),
                ('horario_apertura', models.TimeField(verbose_name='Horario de Apertura')),
                ('horario_cierre', models.TimeField(verbose_name='Horario de Cierre')),
                ('dias_atencion', models.CharField(choices=[('LU-VI', 'Lunes a Viernes'), ('LU-SA', 'Lunes a Sábado'), ('LU-DO', 'Lunes a Domingo'), ('MA-SA', 'Martes a Sábado'), ('TODOS', 'Todos los días'), ('CUSTOM', 'Horario personalizado')], default='LU-VI', max_length=20, verbose_name='Días de Atención')),
                ('tipo_comida', models.CharField(choices=[('CASERA', 'Comida Casera'), ('VEGETARIANA', 'Vegetariana'), ('VEGANA', 'Vegana'), ('MIXTA', 'Mixta'), ('TIPICA', 'Típica Colombiana'), ('INTERNACIONAL', 'Internacional')], default='CASERA', max_length=30, verbose_name='Tipo de Comida')),
                ('servicios_adicionales', models.TextField(blank=True, help_text='Ej: Wifi, Parqueadero, Área infantil', verbose_name='Servicios Adicionales')),
                ('foto_principal', models.ImageField(blank=True, null=True, upload_to='comedores/', verbose_name='Foto Principal')),
                ('estado_activo', models.BooleanField(default=True, verbose_name='Estado Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
            ],
            options={
                'verbose_name': 'Comedor',
                'verbose_name_plural': 'Comedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MenuDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('desayuno', models.TextField(blank=True, verbose_name='Desayuno')),
                ('almuerzo', models.TextField(verbose_name='Almuerzo')),
                ('cena', models.TextField(blank=True, verbose_name='Cena')),
                ('precio_desayuno', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Desayuno')),
                ('precio_almuerzo', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Almuerzo')),
                ('precio_cena', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Cena')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('comedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='comedores.comedor', verbose_name='Comedor')),
            ],
            options={
                'verbose_name': 'Menú Diario',
                'verbose_name_plural': 'Menús Diarios',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('comedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='comedores.comedor', verbose_name='Comedor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comedores_favoritos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'ordering': ['-fecha_agregado'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(help_text='Nombre del usuario si no está registrado', max_length=100, verbose_name='Nombre')),
                ('calificacion', models.IntegerField(help_text='Calificación de 1 a 5 estrellas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación')),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('aprobado', models.BooleanField(default=True, verbose_name='Aprobado')),
                ('comedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='comedores.comedor', verbose_name='Comedor')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_comedores', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='comedor',
            index=models.Index(fields=['estado_activo', 'nombre'], name='comedores_c_estado__c23b78_idx'),
        ),
        migrations.AddIndex(
            model_name='comedor',
            index=models.Index(fields=['barrio'], name='comedores_c_barrio_3da987_idx'),
        ),
        migrations.AddIndex(
            model_name='menudiario',
            index=models.Index(fields=['comedor', '-fecha'], name='comedores_m_comedor_33418b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='menudiario',
            unique_together={('comedor', 'fecha')},
        ),
        migrations.AlterUniqueTogether(
            name='favorito',
            unique_together={('usuario', 'comedor')},
        ),
        migrations.AddIndex(
            model_name='comentario',
            index=models.Index(fields=['comedor', '-fecha'], name='comedores_c_comedor_c8e278_idx'),
        ),
    ]
