# Generated by Django 4.2.7 on 2025-10-21 02:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comedor',
            name='accesible_silla_ruedas',
            field=models.BooleanField(default=False, verbose_name='Accesible en Silla de Ruedas'),
        ),
        migrations.AddField(
            model_name='comedor',
            name='acepta_ninos',
            field=models.BooleanField(default=True, verbose_name='Acepta Niños'),
        ),
        migrations.AddField(
            model_name='comedor',
            name='cola_estimada',
            field=models.CharField(blank=True, default='Sin cola', help_text='Ej: 5-10 minutos, 15-20 minutos', max_length=50, verbose_name='Tiempo de Espera Estimado'),
        ),
        migrations.AddField(
            model_name='comedor',
            name='cupos_disponibles',
            field=models.IntegerField(default=50, help_text='Actualizar diariamente', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cupos Disponibles Hoy'),
        ),
        migrations.AddField(
            model_name='comedor',
            name='distancia_parada',
            field=models.CharField(blank=True, help_text='Ej: 50 metros, 2 cuadras', max_length=50, verbose_name='Distancia a la Parada'),
        ),
        migrations.AddField(
            model_name='comedor',
            name='es_gratuito',
            field=models.BooleanField(default=True, help_text='Marcar si el comedor es completamente gratuito', verbose_name='¿Es Gratuito?'),
        ),
        migrations.AddField(
            model_name='comedor',
            name='parada_bus_cercana',
            field=models.CharField(blank=True, help_text='Nombre de la parada más cercana', max_length=200, verbose_name='Parada de Bus Más Cercana'),
        ),
        migrations.AddField(
            model_name='comedor',
            name='permite_llevar_comida',
            field=models.BooleanField(default=False, help_text='Para llevar a familiares', verbose_name='Permite Llevar Comida a Casa'),
        ),
        migrations.AddField(
            model_name='comedor',
            name='precio_subsidiado',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, help_text='Precio con subsidio si no es gratuito', max_digits=10, null=True, verbose_name='Precio Subsidiado'),
        ),
        migrations.AddField(
            model_name='comedor',
            name='requisitos_acceso',
            field=models.TextField(blank=True, default='Sin requisitos especiales', help_text='Ej: Documento de identidad, Carnet de persona mayor, Sin requisitos', verbose_name='Requisitos de Acceso'),
        ),
        migrations.AddField(
            model_name='comedor',
            name='rutas_transporte_publico',
            field=models.TextField(blank=True, help_text='Ej: Ruta 15, Ruta 20, MIO Estación Flora', verbose_name='Rutas de Transporte Público'),
        ),
        migrations.AddField(
            model_name='comedor',
            name='tiene_area_infantil',
            field=models.BooleanField(default=False, verbose_name='Tiene Área Infantil'),
        ),
        migrations.AddField(
            model_name='comedor',
            name='tiene_banos',
            field=models.BooleanField(default=True, verbose_name='Tiene Baños'),
        ),
        migrations.AddField(
            model_name='comedor',
            name='tiene_rampa',
            field=models.BooleanField(default=False, verbose_name='Tiene Rampa de Acceso'),
        ),
        migrations.AddField(
            model_name='comedor',
            name='tiene_silla_bebes',
            field=models.BooleanField(default=False, verbose_name='Tiene Sillas para Bebés'),
        ),
        migrations.AddField(
            model_name='comedor',
            name='ultima_actualizacion_cupos',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización de Cupos'),
        ),
        migrations.AddField(
            model_name='comedor',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Número de WhatsApp para contacto rápido', max_length=50, verbose_name='WhatsApp'),
        ),
    ]
